### ISSUE TITLE
No Red referenced in cpp serializers benchmark.

### ISSUE THREAD

**Issue by cgyurgyik** [KonanM/tser#1]
https://github.com/KonanM/tser/blob/a4496dcb476d07038421a0818518d1b0f6077c4f/example/example2.cpp#L23

Is the final else supposed to be ```Red``` instead of ```Blue```?

**Comment by KonanM** [comment]
You are completely correct. Fixed with https://github.com/KonanM/tser/commit/7d193f9f54880076fde2ab0f3f662bf173bdfe9d
