### ISSUE TITLE
API mismatch between serializing and deserializing

### ISSUE THREAD

**Issue by brooksprumo** [KonanM/tser#8]
I'm using `tser` to serialize and deserialize some types to and from disk and I noticed the API for serializing and deserializing are mismatched. Serialization produces a non-base64 encoded string internally, but the constructor of `BinaryArchive` takes in a base64-encoded string when deserializing.

To work around this, I either have to base64-encode after serializing and store that, or I need to use `BinaryArchive::initialize()` instead of the constructor. I do not want to store a base64-encoded string because I do not want to increase disk usage unnecessarily.

```cpp
// Serialize to disk
tser::BinaryArchive archive;
archive.save(my_datapoints);
auto archive_view = archive.get_buffer(); // <-- *NOT* base64 encoded
write_buffer_to_disk(my_filepath, archive_view.data(), archive_view.size());
```

However, if I try to deserialize the `archive_view`, it will fail.

```cpp
tser::BinaryArchive archive(archive_view); // using archive_view from above
auto my_datapoints = archive.load<MyDataPoints>(); // this will fail since BinaryArchive expects a base64-encoded string
```

To work-around this, I have to do this:

```cpp
tser::BinaryArchive archive(0); // explicitly set size to 0 so that a 1 KB buffer is not created by default
archive.initialize(archive_view); // using archive_view from above
auto my_datapoints = archive.load<MyDataPoints>();
```

I find this a little strange for an API. I'd expect that `BinaryArchive` would operate on non-base64 encoded strings, and then if printing (or reading in from `stdin`) would perform the base64 encoding.

I'm not sure how you'd like to proceed with this one, hence the Issue instead of a Pull Request. I did want to make you aware of this issue that I ran into personally, in case you have a solution already in mind.

Thank you!

**Comment by KonanM** [comment]
My main use case for tser was to print a BinaryArchieve to the console or a human readable log file and then use that base64 encoded data to intialize a BinaryArchieve again. I have basically designed the API around that use case. I will definitely add an example of writing the binary content to a file and loading it again to make that more clear.

Do you have any ideas on what non breaking changes you would like to see to make your use case easier?

**Comment by brooksprumo** [comment]
I think your use case makes a lot of sense. I don't have a good idea of how to make my use case easier, but maybe it doesn't matter right now, especially if there's an example in the main `README`. I'll spend some time to think about this, and let you know if I come up with anything.

Thanks!

**Comment by KonanM** [comment]
Ok I have added an example with https://github.com/KonanM/tser/commit/7ce2cd9bd102767c2110ab81a5c30c7f419aa53b . I will close this issue for now. Just write a new issue / PR when you have something in mind.
